//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D6, // Low Side 1 (D6)
	Gpio::D7, // Low Side 2 (D7)
	Gpio::D8, // Low Side 3 (D8)
	Gpio::D9, // Low Side 4 (D9)
	Gpio::D10, // Low Side 5 (D10)
	Gpio::D11, // Low Side 6 (D11)
	Gpio::D12, // Low Side 7 (D12)
	Gpio::D13, // Low Side 8 (D13)
	Gpio::D14, // Low Side 9 (D14)
	Gpio::D15, // Low Side 10 (D15)
	Gpio::G2, // Low Side 11 (G2)
	Gpio::G3, // Low Side 12 (G3)
	Gpio::G4, // Low Side 13 (G4)
	Gpio::G5, // Low Side 14 (G5)
	Gpio::G6, // Low Side 15 (G6)
	Gpio::G7, // Low Side 16 (G7)
	Gpio::E15, // High Side 1 (E15)
	Gpio::E14, // High Side 2 (E14)
	Gpio::E13, // High Side 3 (E13)
	Gpio::E12, // High Side 4 (E12)
	Gpio::E11, // High Side 5 (E11)
	Gpio::E10, // High Side 6 (E10)
	Gpio::G8, // High Side 7 (G8)
	Gpio::G15, // High Side 8 (G15)
	Gpio::A8, // Stepper Direction (A8)
	Gpio::C6, // Stepper Control (C6)
	Gpio::C7, // Stepper Disable (C7)
	Gpio::B7, // DBW Disable (B7)
	Gpio::B8, // DBW Control (B8)
	Gpio::B9, // DBW Direction (B9)
// "Low Side 1 (D6)",
// "Low Side 2 (D7)",
// "Low Side 3 (D8)",
// "Low Side 4 (D9)",
// "Low Side 5 (D10)",
// "Low Side 6 (D11)",
// "Low Side 7 (D12)",
// "Low Side 8 (D13)",
// "Low Side 9 (D14)",
// "Low Side 10 (D15)",
// "Low Side 11 (G2)",
// "Low Side 12 (G3)",
// "Low Side 13 (G4)",
// "Low Side 14 (G5)",
// "Low Side 15 (G6)",
// "Low Side 16 (G7)",
// "High Side 1 (E15)",
// "High Side 2 (E14)",
// "High Side 3 (E13)",
// "High Side 4 (E12)",
// "High Side 5 (E11)",
// "High Side 6 (E10)",
// "High Side 7 (G8)",
// "High Side 8 (G15)",
// "Stepper Direction (A8)",
// "Stepper Control (C6)",
// "Stepper Disable (C7)",
// "DBW Disable (B7)",
// "DBW Control (B8)",
// "DBW Direction (B9)",
}
