//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A8: return "Stepper Direction (A8)";
		case Gpio::B7: return "DBW Disable (B7)";
		case Gpio::B8: return "DBW Control (B8)";
		case Gpio::B9: return "DBW Direction (B9)";
		case Gpio::C6: return "Stepper Control (C6)";
		case Gpio::C7: return "Stepper Disable (C7)";
		case Gpio::D10: return "Low Side 5 (D10)";
		case Gpio::D11: return "Low Side 6 (D11)";
		case Gpio::D12: return "Low Side 7 (D12)";
		case Gpio::D13: return "Low Side 8 (D13)";
		case Gpio::D14: return "Low Side 9 (D14)";
		case Gpio::D15: return "Low Side 10 (D15)";
		case Gpio::D2: return "Digital Input 4 (D2)";
		case Gpio::D3: return "Digital Input 3 (D3)";
		case Gpio::D4: return "Digital Input 2 (D4)";
		case Gpio::D5: return "Digital Input 1 (D5)";
		case Gpio::D6: return "Low Side 1 (D6)";
		case Gpio::D7: return "Low Side 2 (D7)";
		case Gpio::D8: return "Low Side 3 (D8)";
		case Gpio::D9: return "Low Side 4 (D9)";
		case Gpio::E10: return "High Side 6 (E10)";
		case Gpio::E11: return "High Side 5 (E11)";
		case Gpio::E12: return "High Side 4 (E12)";
		case Gpio::E13: return "High Side 3 (E13)";
		case Gpio::E14: return "High Side 2 (E14)";
		case Gpio::E15: return "High Side 1 (E15)";
		case Gpio::E2: return "VR1 (E2)";
		case Gpio::E3: return "VR2 (E3)";
		case Gpio::E4: return "VR3 (E4)";
		case Gpio::E5: return "VR4 (E5)";
		case Gpio::E7: return "Hall 2 (E7)";
		case Gpio::E8: return "Hall 4 (E8)";
		case Gpio::E9: return "Hall 3 (E9)";
		case Gpio::F13: return "Hall 5 (F13)";
		case Gpio::F14: return "Hall 6 (F14)";
		case Gpio::F15: return "Hall 8 (F15)";
		case Gpio::G0: return "Hall 7 (G0)";
		case Gpio::G1: return "Hall 1 (G1)";
		case Gpio::G15: return "High Side 8 (G15)";
		case Gpio::G2: return "Low Side 11 (G2)";
		case Gpio::G3: return "Low Side 12 (G3)";
		case Gpio::G4: return "Low Side 13 (G4)";
		case Gpio::G5: return "Low Side 14 (G5)";
		case Gpio::G6: return "Low Side 15 (G6)";
		case Gpio::G7: return "Low Side 16 (G7)";
		case Gpio::G8: return "High Side 7 (G8)";
		default: return nullptr;
	}
	return nullptr;
}
